// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Map = require("bs-platform/lib/js/map.js");
var Int$Jit = require("./int.bs.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function scope_of(param) {
  return param[0];
}

function unwrap_scope(param) {
  return param[1];
}

var compare = Caml_obj.caml_compare;

var M_state = $$Map.Make({
      compare: compare
    });

var M_int = $$Map.Make(Int$Jit);

exports.scope_of = scope_of;
exports.unwrap_scope = unwrap_scope;
exports.M_state = M_state;
exports.M_int = M_int;
/* M_state Not a pure module */
