// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function add(a, l) {
  if (!l) {
    return /* :: */[
            a,
            /* [] */0
          ];
  }
  var x = l[0];
  if (Caml_obj.caml_equal(a, x)) {
    return l;
  } else {
    return /* :: */[
            x,
            add(a, l[1])
          ];
  }
}

var mem = List.mem;

exports.add = add;
exports.mem = mem;
/* No side effect */
